/*
 * This source file was generated by the Gradle 'init' task
 */
package game_engine_opengl2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        launcher classUnderTest = new launcher();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
